### ISSUE TITLE
Unable to communicate with Deemix

### ISSUE THREAD

**Issue by dfatih** [youegraillot/lidarr-on-steroids#105]
**Describe the bug**
After the update to the latest version im getting Demix error:
Unable to communicate with Deemix. Method not found: 'NzbDrone.Core.Download.DownloadClientItemClientInfo NzbDrone.Core.Download.DownloadClientItemClientInfo.FromDownloadClient(NzbDrone.Core.Download.DownloadClientBase`1<!!0>)'.

**Screenshots**
![image](https://github.com/user-attachments/assets/91fca2c2-0ae9-4e2b-8051-629b955faa86)

**System info (please complete the following information):**
 - OS: Synology NAS
 - Container engine 

**docker-compose.yml (please complete the following information):**
```yml
lidarr:
    container_name: TrashGuide-Lidarr
    image: youegraillot/lidarr-on-steroids
    environment:
      - FLAC2CUSTOM_ARGS=-a "-vn -c:a libopus -b:a 64k" -e .opus -r '\.mp3$$'
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/lidarr:/config
      - ${DOCKERCONFDIR}/deemix:/config_deemix
      - ${DOCKERCONFDIR}/deemix/downloads:/deemix/downloads
      - ${DOCKERDOWNLOADDIR}/completed:/downloads/completed
      - ${DOCKERSTORAGEDIR}/Music:/data/media
    restart: unless-stopped
```
