### ISSUE TITLE
Deemix indexer stopped working

### ISSUE THREAD

**Issue by Stooovie** [youegraillot/lidarr-on-steroids#110]
**Describe the bug**
After months of flawless operation, Lidarr (v 2.5.1.4312) on Steroids can not connect to the Deemix indexer.

`Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Connection refused (localhost:6595)
`
**To Reproduce**
1) open Deemix indexer options
2) test
3) it fails

**Expected behavior**
Indexer not to fail.

**System info (please complete the following information):**
 - OS: Dockge inside Proxmox LXC
 - Docker 27.2.0

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - 8686:8686 # Lidarr web UI
      - 6595:6595 # Deemix web UI
    volumes:
      - /media/config:/config
      - /media/config_deemix:/config_deemix
      - Public:/media/Public:rw
      - /media/downloads:/downloads
    environment:
      - PUID=0
      - PGID=0
networks: {}
volumes:
  Public:
    driver: local
    driver_opts:
      type: none
      device: /media/Public
      o: bind
```

**Additional context**
It is NOT caused by wrong ARL. I can open Deemix and it can download songs. Deemix as a Download Client does work. Setting the actual IP instead of <localhost> did not help. There have been no changes to networking or the container overall.

LOGS ARE HERE:
[lidarr.debug.txt
](https://oshi.at/zEjy)
[lidarr.txt](https://oshi.at/WTBp)

EDIT: It's even weirder. I have restored a backup of the LXC I run LoS from, and it worked for a couple of hours. And then stopped working with the above error again.
