### ISSUE TITLE
~50% success rate finding albums in deezer

### ISSUE THREAD

**Issue by SecureB00t** [youegraillot/lidarr-on-steroids#118]
**Describe the bug**
When searching/monitoring an album or artist in Lidarr, it will only successfully pull the music from deezer about 1/2 the time. This happens when both searching for artist discographies and individual albums. The desired albums are in Deezer, they are just not found from Lidarr

**To Reproduce**
1. Go to search in Lidarr
2. Search for Artist or Album Name (ie "ABBA"
3. Configure download and monitoring
4. Go to Activity
5. See successfully found albums
6. Go to wanted 
7. See not found albums
8. Go to Deezer
9. Search for not found albums and see that it exists

**Expected behavior**
When I search for an album in Lidarr, it should be pulled from Deezer if it exists

**System info (please complete the following information):**
 - OS: TrueNAS Scale
 - Container engine: Docker

**docker-compose.yml (please complete the following information):**
```yml
services:
  lidarr:
    environment:
      - PUID=0
      - PGID=0
    image: youegraillot/lidarr-on-steroids
    ports:
      - '8686:8686'
      - '6595:6595'
    restart: unless-stopped
    volumes:
      - /mnt/MegaBITE/appdata/lidarr/config:/config
      - /mnt/MegaBITE/appdata/lidarr/config-deemix:/config_deemix
      - /mnt/MegaBITE/appdata/lidarr/downloads:/downloads
      - /mnt/MegaBITE/appdata/lidarr/music:/music
      - >-
        /mnt/MegaBITE/appdata/ProtonVPN/config/qBittorrent/downloads:/config/qBittorrent/downloads
      - /mnt/MegaBITE/theKitchenSink/Plex:/PlexData
version: '3'

```
