### ISSUE TITLE
Valid Notifarr API key refused as Invalid

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#25]
**Describe the bug**
When I try to connect Lidarr On Steroids to Notifiarr it says 
"Unable to send notification. Ensure Lidarr Integration is enabled & assigned a channel on Notifiarr"
This is not true, LOS integration is enabled, assigned a channel and responds 200 OK on Notifiarr Client.
LOS refuses both general Notifiarr API key and specifically created API key.
All other *arr apps work with same API key, including vanilla Lidarr. 
I have recently installed LOS from scratch and it works fine (doesn't crash anymore like last summer when grabbing from Deemix), except for this thing.

**To Reproduce**
1. Go to Settings/Connect
2. Press +
3. Add Notification -> Notifiarr
4. Enter Notifiarr API key and Notifiarr name
5. Press Test

**Expected behavior**
It should respond OK and let save the connection, then send notifications to Discord on grab/import/etc

**Screenshots**
See below

**System info (please complete the following information):**
 - OS: Open Media Valult
 - Docker latest

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads/music
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
 ```

**Additional context**
If you look at lower right corner you see the confirmed connection test to Lidarr On Steroids, so everything seems to work fine from Notifiarr to LOS, but not from LOS to Notifiarr. 

![notifiarr](https://user-images.githubusercontent.com/55061479/207063651-91754262-2afa-40e5-82e5-957180720509.jpg)

Here you can see Notifiarr is connected and working and it shows vanilla Lidarr as red because it's offline and Lidarr On Steroids as green because it's online.

![notifiarr integration](https://user-images.githubusercontent.com/55061479/207065435-74b4f4f3-625a-4a3e-b0dd-bf8bf5bf2471.jpg)

Here is the error when trying to connect LOS to Notifiarr with API key

![LOSnotifiarr](https://user-images.githubusercontent.com/55061479/207064622-bd5c95a0-37d5-42cb-a853-34fc075a3bfa.jpg)
