### ISSUE TITLE
Calendar ignored by Deemix

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#31]
**Describe the bug**
LOS completely ignores calendar releases, so even if they are available, Deemix isn't triggered to download them. 

**To Reproduce**
1. Disable all torrent/usenet indexers and clients, leave only Deemix active
2. Wait

**Expected behavior**
When something is released according to calendar, Deemix should be triggered and look for it.

**What happens instead**
Nothing, Deemix is never triggered. But if you manually search new albums, it downloads them.

**Screenshots**
---

**System info (please complete the following information):**
 - OS: Openmediavault
 - Docker latest

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
```

**Additional context**
---
