### ISSUE TITLE
Useless library scans for each new album found

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#32]
**Describe the bug**
This is probably a specifically Lidarr-related bug, but I'll report anyway. 
Each time LOS finds an album
- it starts downloading it
- it starts a full library scan
- if albums added are more than one, scan repeats as many times
- downloads get stuck with purple icon until all HDD thrashing is finished

**To Reproduce**
1. Search for an album or wait for any client to be triggered
2. Watch LOS hog the system

**Expected behavior**
Library scan should be periodic or manual, not happen right when LOS downloads something.

**Screenshots**
---

**System info (please complete the following information):**
 - OS: Openmediavault
 - Docker latest

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
```

**Additional context**
Last december I tried a whole Wanted scan. LOS found 554 albums and got stuck scanning Library over and over for 2 weeks, until I killed it. I have about 32k albums. A person with a few albums probably doesn't experience this, as there is only a few things to scan, but it shouldn't happen anyway.
