### ISSUE TITLE
Client/Indexer priority not honored

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#34]
**Describe the bug**
When both usenet/torrent AND deemix indexers/clients are enabled, LOS always chooses usenet/torrent.

**To Reproduce**
1. Enable all types of clients and indexers
2. set priority of deemix client/indexer to 1
3. set priority of usenet/torrent clients/indexers to 30
4. Manually search for an artist on Deemix client (or Deezer web page) and make sure it's available, do not download
5. Search the same artist from LOS

**Expected behavior**
Given the above priority, LOS should immediately download all available albums from Deemix.

**What happens instead°°
LOS downloads from torrent or usenet the same albums that are available on Deezer, and NEVER from Deemix.
If there are 10 albums available on Deemix, LOS downloads 5 from usenet/torrent and ignores the other 5 available only on Deemix.
LOS downloads correctly from Deemix ONLY if Deemix is the only client/indexer enabled.

**Screenshots**
---

**System info (please complete the following information):**
 - OS: Openmediavault
 - docker latest

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
```

**Additional context**
To make a comparison to a similar scenario, on Radarr and Sonarr, if I manually download something from usenet/torrent and that object is present in library, it is automatically recognized and associated to its relative entry, so when download is complete, it is imported as if it was downloaded from Radar/Sonarr (not always, sometimes filenames are just wrong, but let's consider only successful cases). If I do the same on LOS and manually download something from Deemix, it is refused by LOS and blocked with yellow icon because "it was not downloaded from client/not in any category". But if I click the little man icon for manual import, all yellowed albums are perfectly recognized and imported with no need to tweak anything.
