### ISSUE TITLE
Deemix doesn't work anymore

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#44]
**Describe the bug**
Not only Deemix never starts/searches for albums on RSS feeds (see my previous reports), but now it doesn't find anything manually. It does not find albums that are available. I have premium subscription, I can find and download those albums from Deemix WebGUI, but not anymore from Lidarr.

**To Reproduce**
1. Disable all indexers/clients other than Deemix
2. Manually search any album from calendar or artist pages

**Expected behavior**
Deemix should find the albums and download them from Lidarr. 
Instead it just says "Completed" and does nothing.

**System info (please complete the following information):**
 - Latest docker

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
```
