### ISSUE TITLE
Lidarr unable to match albums from Deemix

### ISSUE THREAD

**Issue by TheMinecraftGuyGuru** [youegraillot/lidarr-on-steroids#45]
**Describe the bug**
When downloading many certain albums I get an error from Lidarr after its been downloaded that "One or more albums expected in this release were not imported or missing" I have 14 pages of these sitting in my queue, there are others that import fine however

**To Reproduce**
try importing any of these albums:
  |   | Against the Current | Infinity | FLAC |   | - |   |  
  |   | Afrojack | Keep It Low | FLAC |   | - |   |  
  |   | Akon | Smack That | FLAC |   | - |   |  
  |   | A$AP Rocky | Cocky | FLAC |   | - |   |  
  |   | 5 Seconds of Summer | Want You Back | FLAC |   | - |   |  
  |   | AWOLNATION | The Best | FLAC |   | - |   |  
  |   | Alec Benjamin | Mind Is a Prison | FLAC |   | - |   |  

again I have 14 pages of these, this is just an example

**Expected behavior**
it should import them

**System info (please complete the following information):**
 - OS: Ubuntu Server, running Portainer for management
 - Container engine 20.10.23

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - /dockerconfig/lidarr-steroids/config:/config
      - /dockerconfig/lidarr-steroids/config_deemix:/config_deemix
      - /mnt/torrents/deemix_downloads:/downloads
      - /mnt/media/music:/music
    networks:
      - WAN
      - tunnel

networks:
  tunnel:
    external: true
  WAN:
    external: true
```
