### ISSUE TITLE
Recent albums not downloaded because "Album duration is 0, unable to validate size until it is available"

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#48]
**Describe the bug**
LOS does not fire Deemix if Usenet and Torrent indexers are enabled, I already wrote about this, so every now and then I check the calendar, disable all Usenet and Torrent stuff and manually search for not downloaded albums. Most of the times they are available on Deezer, but they are shown with red icon stating "Album duration is 0, unable to validate size until it is available". But they are all available, they are from past weeks/months and can be played on Deezer. When I force download them, they are perfectly fine, so something has changed in Deezer that confuses Deemix or LOS.

**To Reproduce**
1. Go to calendar
2. choose any non downloaded album
3. manually search for it from its Artist page
4. Deemix icons will be red stating the above error
5. Download anyway
6. Album is downloaded and fine

**Expected behavior**
All the above should happen automatically

**Screenshots**
Eh, I decided to notify the issue after having downloaded everything I could. But It's just red icon with above message beside albums found by Deemix engine.

**System info (please complete the following information):**
 - Open Media Vault 6
 - Docker latest

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
```
