### ISSUE TITLE
Missing Release Group tag

### ISSUE THREAD

**Issue by Abraka** [youegraillot/lidarr-on-steroids#50]
**Describe the bug**
When downloading new albums, nothing is imported and stays in queue because there is missing "Release group" tag.

**Screenshots**
![dmLid1](https://github.com/youegraillot/lidarr-on-steroids/assets/6759588/c54cb462-88ad-4978-8288-f636af691ba7)

**System info (please complete the following information):**
 - OS:  rocky linux
 - Container engine latest docker

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /home/lidarr-deemix/config:/config
      - /home/lidarr-deemix/config_deemix:/config_deemix
      - /home/lidarr-deemix/downloads:/downloads
      - /home/lidarr-deemix/music:/music
```
