### ISSUE TITLE
Empty folders being removed from downloads

### ISSUE THREAD

**Issue by SickProdigy** [youegraillot/lidarr-on-steroids#59]
**Describe the bug**
Folder in /downloads/ that are empty are automatically removed. I think it is mainly due to deemix. Just wondering if anyone has a workaround.

**To Reproduce**
1. Run Lidarr-on-steroids
2. Add empty folders inside of /downloads/ location
3. Import music from deemix
4. Wait for it to scan empty folders and delete all inside of downloads location mount.

**Expected behavior**
[Error] clean-downloads.sh: Info|Lidarr event: AlbumDownload 
[Error] clean-downloads.sh: Info|Cleaning empty folders 
[Error] clean-downloads.sh: /downloads/nzbget/completed/Lidarr-music 
[Error] clean-downloads.sh: /downloads/deemix/50 Cent/50 Cent - Best Friend (Remix) 
[Error] clean-downloads.sh: /downloads/_torrent/watched 
[Error] clean-downloads.sh: find: cannot delete ‘/downloads/_torrent/watched’: Permission denied 

Was hoping that folders outside of /downloads/deemix would stay and anything inside would do it's thing. I've changed the folder inside of deemix to this location. Additional information below.

**System info (please complete the following information):**
 - OS: ubuntu, 
 - Docker version 24.0.4

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /home/user/Documents/docker-containers/lidarr-on-steroids:/config
      - /home/user/Documents/docker-containers/lidarr-on-steroids/deemix:/config_deemix
      - /srv/samba/media/unsorted:/downloads
      - /srv/samba/media/Music/Music-Library:/music
    networks:
      homelab:
        aliases:
          - lidarr
          - deemix
networks:
  homelab:
    name: homelab
    external: true
```

**Additional context**
I've also tried mounting the deemix folder directly, but it has issues with my other download clients. Can't find their download location if I narrow it too far. Although I guess I wouldn't need them as long as deemix could find everything. Just kind of stuck with what I should do here. It keeps deleting empty folders inside of /downloads/nzbget/completed/ which causes errors with arr clients using nzbget at the moment. If deemix could just not clean all empty folders would be perfect.
