### ISSUE TITLE
Lidarr not recognising Deemix as indexer or download client

### ISSUE THREAD

**Issue by kaibagley** [youegraillot/lidarr-on-steroids#64]
**Describe the bug**
Lidarr not seeing Deemix as download client or indexer

**To Reproduce**
1. Fresh install of LoS
OR
1. Have LoS running and working as usual

**Expected behavior**
Lidarr and Deemix work together in harmony forever

**System info (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Container engine 24.0.5, build ced0996

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
...
services:
lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /server/lidarr/lidarr:/config
      - /server/lidarr/deemix:/config_deemix
      - /server/music/downloads:/downloads
      - /server/music/music:/music
      - ...
```

**Additional context**
LoS has been working perfectly for a week or so, downloaded 12k songs etc etc, and suddenly getting a red 4 next to System, saying it has no indexers, download clients, and update available.

Docker logs don't really say anything that didn't exist before, millions of lines of this:

`[Info] Lidarr.Http.Authentication.ApiKeyAuthenticationHandler: AuthenticationScheme: API was challenged`

Thanks for any help!
