### ISSUE TITLE
Unable to link to deezer as Indexer

### ISSUE THREAD

**Issue by 20-goto-10** [youegraillot/lidarr-on-steroids#84]
Probably user error, but Installed 1.4.1.3564 and it successfully links to connects to Deemix as download client, however I cannot get it to connect the Deemix as the indexer.

**Describe the bug**
In the indexer config page, I Click + to add new indexer. Select Deemix from Others.
Enter (defaulted to) http://localhost:6595 and arl, click test but connection times out. 

**To Reproduce**
1. Go to Indexers -> Plus -> Select Deemix
2. Use default http://localhost:6595 for Deemix url
3. Add arl
4. Click test
5. After a few minutes see 

**Expected behavior**

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu server 2023
 - Container engine Docker 24.0.7

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids:latest
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /opt/lidarr/config:/config
      - /opt/lidarr/demix/config:/config_deemix
      - /mnt/shared-media/lidarr/downloads:/downloads
      - /mnt/shared-media/lidarr/music:/music
```

**Additional context**
Tried using localhost, 127.0.0.1, explicit ip address and host.docker.internal. 
Note that the downloader which uses localhost 6595 test button does work
