### ISSUE TITLE
Download wasn't grabbed by Lidarr and not in a category, Skipping.

### ISSUE THREAD

**Issue by ruvido** [youegraillot/lidarr-on-steroids#89]
Fresh install on debian and docker compose. Added my ARL and logged in in deemiz. When I request a track in deemix, the track is downloaded but appears in Lidarr in Queue with an orange icon on the left with a helper saying:

Download wasn't grabbed by Lidarr and not in a category, Skipping.

Files are in the deemix folder (/download) and not moved by Lidarr to proper directory (/music). 

What did I miss in the config?

Just fyi, this is my docker compose (only the relevant part)

```
lidarr:
      image: youegraillot/lidarr-on-steroids
      restart: unless-stopped
      ports:
        - "8686:8686" # Lidarr web UI
        - "6595:6595" # Deemix web UI
      volumes:
        - ./lidarr_config:/config
        - ./deemix_config:/config_deemix
        - /media/deemix/downloads:/downloads
        - /media/music:/music

```
Thanks a lot for your help
