### ISSUE TITLE
[ERROR] Couldnt Connect to Local Server

### ISSUE THREAD

**Issue by dfatih** [youegraillot/lidarr-on-steroids#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. windows, ubuntu]
 - Container engine [e.g. docker 20.10]

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /volume1/docker/lidarr/config:/config
      - /volume1/docker/lidarr/deemix:/config_deemix
      - /volume1/Downloads/completed:/data/downloads
      - /volume1/Media/Music:/data/music
```

**Additional context**
Installed the Container on my Synology NAS.
And making Lidarr accessable through reverse proxy.
lidarr.my.domain.me works fine but with deemix.my.domain.me i get the error Couldm't connect to local Server.
