### ISSUE TITLE
[SOLVED] Deemix downloads fail if triggered by Lidarr, but not by Deemix itself

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#96]
**Describe the bug**
Since a few days I noticed that if I manually search for an album and it's available on Deezer, when I click the download button on Lidarr, Deemix starts downloading, but fails every single track with "Track not available on Deezer's servers and no alternative found!".
In the Deemix GUI on the upper right corner I can see the album cover with red failed exclamation mark. If I click the exclamation icon, which is a "retry" button, the album downloads fine with no error. 

**To Reproduce**
1. Go to any artist page
2. Click on manual search button beside a missing album
3. Choose the Deemix indexer rip if available
4. Open Deemix GUI
5. Check the upper corner for the album -> the album failed download
6. Click the exclamation icon to redownload -> the album is normally downloaded

**Expected behavior**
Album should be downloaded and grabbed from Deezer unattended.

**Screenshots**

**System info (please complete the following information):**
 - OS: OMV6
 - Container engine: docker 25

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/LidarrOnSteroids:/config
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Deemix:/config_deemix
      - /srv/dev-disk-by-uuid-BAF04088F0404D37/data/downloads/music:/downloads
      - /srv/dev-disk-by-uuid-BAF04088F0404D37/data/media/music:/music
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data:/data
      - /srv/dev-disk-by-uuid-A870CA6B70CA3FB4/data:/data2
      - /srv/dev-disk-by-uuid-BAF04088F0404D37/data:/data3
    environment:
      - TZ=Europe/Rome
      - PUID=998
      - PGID=100
      - AUTOCONFIG=true
      - FLAC2CUSTOM_ARGS=true
      - DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest
      
networks:
  omv1:
    external: true
```

**Additional context**
Nothing changed in the system from my side. It just started doing this. 

EDIT
Nevermind, a simple restart of the container fixed the problem.
