### ISSUE TITLE
Download not working on deemix UI

### ISSUE THREAD

**Issue by eojjn** [youegraillot/lidarr-on-steroids#98]
**Describe the bug**
Clicking download does not add download to queue...nothing happens.

**To Reproduce**
search for album
click download
nothing happens

**Expected behavior**
download should be queued 

**System info (please complete the following information):**
alpine linux

**docker-compose.yml (please complete the following information):**
```yml
version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    container_name: lidarr
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - /home/x/lidarr:/config
      - /home/x/Music/Processed:/music
      - /data:/data
      - /home/x/deemix:/config_deemix
      - /home/x/Music/Unprocessed:/downloads

```

**Additional context**
